### ISSUE TITLE
Restrict installation prompt

### ISSUE THREAD

**Issue by arnaud-1510** [dynamsoft-dwt/angular-cli-application#1]
I been trying to restrict to an specific component the installation prompt for the plugin is this possible using this package, do you have any sort of guide or tutorial for this also I've read the docs and haven't found anything related to this.

Any ideas in how to solve this?

**Comment by chloe-hahn** [comment]
Is this what you are looking for? https://developer.dynamsoft.com/dwt/kb/2894

**Comment by arnaud-1510** [comment]
@chloe-hahn thanks for you response.

The link you post is for customizing the prompt no to restrict to an specific component.

Anyway after some research I was able to workaround this by only including the dynamo scripts only at the component that it suppose to be using the web twain plugin, also I've changed the default dialog and fire a javascript event that then gets handled by an angular listener to show an entire different dialog. 

Again thanks for your help.
