### ISSUE TITLE
How to use SelectSource() with asynchronous function in angular?

### ISSUE THREAD

**Issue by ankworld** [dynamsoft-dwt/angular-cli-application#3]
# DWT 15.2.0

I find that SelectSource() can use with optional parameter to be async function. The example is work in JS but not in TS because it got unexpected arguments.

**Comment by Tom-Dynamsoft** [comment]
@ankworld  That's because the type definition for the API SelectSource is not complete, I'll contact the team to get it updated asap. Thanks for your feedback
