### ISSUE TITLE
How is this different from the "Scan-Documents-with-Angular" sample?

### ISSUE THREAD

**Issue by leopignataro** [dynamsoft-dwt/angular-cli-application#6]
Dear Dynamsoft team,

At the moment [I am unable to run this sample](https://github.com/dynamsoft-dwt/angular-cli-application/issues/5).

However, I also found the [Scan-Documents-with-Angular](https://www.dynamsoft.com/Downloads/WebTWAIN-Sample-Download.aspx?SampleID=198) on your website, which seems to be very similar. Incidentally, I **can** run that sample.

Why are there two samples seemingly for the same purpose? Or is there a fundamental difference? Which is more modern / actively maintained? Should I give preference to either of the samples?

Thanks!

**Comment by Tom-Dynamsoft** [comment]
`angular-cli-application` is based on
    "@angular/cli": "~8.1.0",
`Scan-Documents-with-Angular` is based on 
    "@angular/cli": "~7.3.8",

The first one is just a very simple implementation of the Dynamic Web TWAIN library with Angular while the 2nd one tries to remake the [demo](https://demo.dynamsoft.com/dwt/online_demo_scan.aspx) in an angular application. So if you'd like to see more features, the 2nd one is recommended. If you'd like to start from the very basic features, you can use the 1st one
